apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: TEAM-IND
  title: Team India
  description: Team A created for testing
spec:
  type: team
  children: []
  members: [amit.sahoo@nagarro.com]
  profile: 
    email: team-ind@example.com
    picture: https://media.licdn.com/dms/image/v2/D4D03AQG5simXHpT0sA/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1698875062801?e=2147483647&v=beta&t=ZCuf9g4fYED4f-WAHrlBkHl1N1VpnDBTZJujC7kXf04 